* PHILIPPINE ECONOMIC DEVELOPMENT
** OBJECTIVES
1. read the test entitled "need for more study Philippine
   Economic Development"

2. share ideas

3. to supply a fairer view of Filipino Participation and
   Supplement the Defecive Spanish Accounts

** CONTENT
*** Agriculture
At the time of the arrival of the spaniards, agriculture in
the Philippines was in a omparatively prosperous condition

The filipinos cultivated rice, which as today, formed their
chief  article   of  food,  They  also   grew  sugar-canes,
coconuts, indigo, sweet potatoes  and other tubers, various
kinds  of  bananas,  the   betel-nut  palm,  the  tamarind,
Iansone, and several varieties of legumes, etc.

With the  coming of the  Spaniards, very many  plants wihch
are commonly  considered to be indigenous  in this country,
were   introduced,  The   most  important   economic  plant
important since  Spanish discovery  was the  tobacco, which
today  forms one  of the  staple crops,  the cacao  nut was
important, the pineapple and etc.

*** Livestock
This  Filipinos  at  the  time od  discovery  had  domestic
animals,  dogs,  cats,  pigs,   goats  and  buffaloes,  i.e
carabaos.

"There  were no  horses nor  mares, the  islands until  the
Spaniards had them brought from China to nowhere else"

It has been truly said that the Filipinos has been affected
by the  centuries of  Spanish coverignty  far less  on this
material side that he has on  his spiritual, For as we read
the early accounts  about agricultural life at  the time of
discovery  and conquest,  and  compare it  with  that of  a
decade ago

Then, the women did most of  the work pounding the rice for
use, whereas today, the men do it, furthermore in the early
days, the system of irrigating the rice fields that is used
today  was known  and practiced,  of course,  the so-called
caingini   method  of   cultiviation  prevailed,   but  the
considerable   of  rice   which  as   various  times   were
contributed by the Filipinos for the support of the Spanish
conquerers

*** Landholding
The lands of  the ancient Filipinos were  divided among the
whole barangay,  so that  each one had  his holding  and no
resident  of one  barangay was  allowed cultivate  lands in
another barangay unless he had aquired them by inheritance,
gift purchase,

In some  barangays, the lands  belong to the  chief through
purchase from the original owners

with the coming of the spaniards, lands were assignd to the
colonists, of  which they were to  have perpetual ownership
after four years;  residence, It is in  connection with the
administration of these encomiendas that we find the annals
of the  Philippines many  accounts of abuses  and exortions
practiced on the natives and the consequent exile

however,  be  supposed  that the  Filipinos  were  actually
disposed  of  their  lands   by  the  kind,  for  althought
according to the  constituional law of the  Indies that and
the soil in all colonies where the doman of the kind..(?)

*** Ship Building
One  of the  most important  industries in  the Philippines
during this  period waas  shipbuilding, we  wouls naturally
expect this  industry to be developed  among the Filipinos,
for they belond to a  seafaring race that for centuries had
been pushing  their way northward and  taking possession of
islands  of tihs  part  of the  Pacific, furthermore,  once
settled in this country, they  hand abundant supply of good
timber for  building purposes, Morga described  the various
kinds of ships and boats used by the Filipinos..

*** Fishing
as next to rice, fish formed  an important part of the diet
of  the Filipinos,  we  find them  engaged  to the  fishing
industry at  the time  of discovery and  conquest, Magellan
and his party saw many fishing boats near the coasts of the
islands passed by them

Most of the devices used today for catching fish were known
then to the ancient Filipinos

*** Metal work and Mining
The early  accounts abound  in glowing descriptions  of the
mining wealth of this country

Chief  among  the  industries connected  with  the  various
kiinds  of   palms,  found  in  the   Philippines  was  the
distillation of  the sap into  alcohol, a process  known to
the Filipinos known long before Spanish arrival

Their drink is a wine made  from the tops of coco, and nipa
palm, of which  there is a great abundance.  They are grown
and tended like vineyards


*** Textile industry
Weaving  was  one  of  the  industries  well-known  to  the
Filipinos  long   before  the  coming  of   the  Spaniards,
Contemporary  writers  speak  of   the  great  quantity  of
clothes, especially cotton, woven in the country

*** Miscellanous Industry
Tha  the Filipinos  first seen  by the  Spaniards were  not
wandering  savages,  as  commonly   assumed  by  later  day
writers, is shown  by the manner in which  they built their
own houses- which  very much resembled those  of today, and
fixed their settlements, It is from such and other similiar
facts that Rizal,, and other  writers claimed for the early
Filipinos a higher  degree of culutre that  they were given
credit for 
