* REFEREBCES OR WORKS CITED (APA, 7th EDITION)
** OBJECTIVES
** CONTENT
*** FORMATTING A REFERENCE LIST
1. Your reference list should appear..

*** BASIC RULES
1. All author's  named should  be inverted (i.e  last names
   should be provided)

2. Author's first  and middle names  should be writte  n as
   initials

3.  If  a middle  name isnt  available, just  initialize the
   author's first name [ex. "Smith j."]

4. Give the  last name  and first  middle initials  for all
   author's of  a particular  work up  to and  including 20
   authors (this is  a new rule, as APA 6  only reuired the
   first six authors), Seperate each author's initials from
   the  next  author in  the  list  with  a comma,  Use  an
   ampersand (&)  before the  last author's name.  If there
   are  21  or  more  authors,  use  an  ellipsis  (but  no
   ampersand)

5. Reference  list entries  should be  alphabetized by  the
   last name of the first author of each work

6. For  multiple articles  by the  same author,  or authors
   listed  in   the  same   order,  list  the   entries  in
   chronological order, from earliest to most recent

7.  When  referring  to  the  titles  of  books,  chapters,
   articles, reports, webpages or other sources, capitzlize
   only the first letter..

8. Italizcize titles of longer works (e.g books)

9. ??

*** BASIC RULES FOR ARTICLES
1. Present journal titles in full
2. Italicize journal titles.
3. Maintain any  nonstandard punctuation and capitalization
   that is used by the journal in its title

   Ex. you should use PhiliSOPHIA instead of Philosophia.

4. Capitalize  all major words  in the titles  of journals,
   Note that  this differs from  the rule of  titling other
   common sources (like books, etc.)

5. Capitalize the first word of the titles and subtitles of
   journal articles,  as well  as the  first word  oafter a
   colon..

6. ??

7. Do not enclose the article title in quotes
   Ex.  Deep  blue; The  mysteries of the  Marianas Trench
        (dont include this shit on the quotes)


** PART 2
*** SINGLE AUTHOR
eLast name first followed by author initials

*** THREE TO TWENTY AUTHORS
List  by last  named  an initials,  commas separate  author
names  while the  last  author name  is  preceded again  by
ampersan

*** MORE THAN TWENTY AUTHORS
List  by last  names and  initials, commas  separate author
names, After the 19 authors names, use an ellipsis in p;ace
of  the remaining  author names,  Then end  with the  final
author's name (do  not place an ampersand  before it) There
should  be no  more than  twenty names  in the  citation in
total.

** BOOKS
Note: If  available, APA 7  reuires a DOI  (Digital Obbject
Identifier) for all  works that have one-  whether print or
digital.

*** BASIC FORMAT
Author,  A.  A. ,  (Year  of  publication), TItle  of  wok,
Capital letter, also for  subtitle, Publisher name, DOI (if
available)

*** EDITED BOOK, NO AUTHOR
Editor, E.  E (Ed), (Year  of Publication), Title  of work,
Capital  letter  also  for  subtitle,  Publisher,  DOI  (if
available)

*** EDITED BOOK WITH AN AUTHOR OR AUTHORS
Author, A, A. (year of publication), Title of work: Capital
letter also  for subtitle  (E. Editor, Ed).  Publisher, DOI
(if available)

Start with the initials first :),  you also have to put the
original work publishing date since its original

*** TRANSLATION
Author, A. A (Year of  publication), Title of work: Capital
letter also for subtitlle (T. Translate, Trans). Publsiher,
(original work published YEAR) DOI (if available)

REMEMBER:  DOI  will  always  in the  last  part  of  every
           citation format,

NOTE: When you cite a republished work, like the one above,
in  your text,  it  should appear  with  both dates:  Plato
(385/378/1989)

*** EDITION OTHER THAN THE FIRST
Author, A.A. (Year of  publication). Title of work: Capital
Letter also  for subtitle  (# edition). Publisher,  DOI (if
available)

*** ARTICLE OR CHAPTER IN AN EDITED BOOK
Author, A.A, *& Author, B.B (Year of publication), Title of
chapter in E.E  Editor & F.F editor (Eds.),  Title of workL
capital   Latter   also   for  subtitle   (pp.   pages   of
chapter). Publisher. DOI (if available)


**** NOTE:
When  you  list the  patges  of  the  chapter or  essay  in
pranthese  after  the  book  title, use  "[[/"  before  the
numbers (pp.  1-21), THis abbreviateion, however,  does not
appear before  the page  numbers in  periodical references,
List any edition  number in the same set  of parentheses as
the  pages  numbers,  separated   by  a  comma:  (2nd  ed.,
pp. 66-72).


** PART 3
NOTE: Some electronic citations necessitate the use of
brackets should directly surround their content without
speaces (e.g, [bracketed content] should like this

*** ELECTRONIC SOURCES
**** INDIVIDUAL
If the page names an individual author, cite their name
first

**** ORGANIZATION
If the resource was written by a group or organization, use
the    name    of    the    group/organization    as    the
author. Additionally, If  the author and site  name are the
same, omit the site name from the citation

GROUP  NAME.  (Year.  Month.  Date)  Title  of  page.  Site
name. URL

Ex.  American  Society for  the  Prevention  of Cruelty  to
Animals (2019,  November 21).  Justive served.  Case closed
for over 40 dogfighting victims

https://www.aspca.org/news/justice-served-case-closed-over-40-dogsfighting-victims

**** AUTHOR NOT LISTED?
If the  page's author is  not listed, start with  the title
instead,  Aditionally, include  a retrieval  date when  the
page's content  is likely  to change  over time  (like, for
instance, if you're citiing a wiki that is publicly edited)

Title  of page,  (Year, Month  Date). Site  name, Retrieved
Month Date, Year, from URL

Tuscan white bean pasta. (2018, February 25). Budgetbytes

**** DATE NOT LISTED?
If  the  date  of  publication   is  not  listed,  use  the
abbreviation (n.d).

Author or  Group name. (n.d)  Title of page. Site  name (if
applicable). URL

**** WIKIPEDIA ARTICLES
APA  7 treats  Wikipedia articles  as special  instances of
entries  in   reference  works,  Thus,  there   are  a  few
differences   between  reference,   entries  of   pages  on
WIkipedia and those of generic webpages

Title of article (YEAR, MONTH,  DATE), IN WIKIPEDIA. URL of
archived version of page

EX.   Quantum    mechanics   (2019,   November    19).   In
wikipedia. [insert said link]

NOTE: Wikipedia articles often  update frequently, for this
reason, the date refers to  the date that the cited version
of  the  page was  published,  Note  also that  the  manual
recommends  linking to  the archived  version of  the page,
rather than  the current version  of the page on  the site,
since the latter  can change over time,  Acess the archived
version  by  clickying  "View  Hisotry"  then  clcking  the
date/timestamp of the version you'd like to cite.

**** ONLINE SCHOLARLY JOURNAL ARTICLE: CITING DOIS
Please  Note:  Because  online  materials  can  potentially
change  URLs, APA  recommends  providing  a Digital  Object
Identifier (DOI) when it is available, as opposed to URLs

Note  also  that  some  online  bibliographies  provide  an
article's DOI but may "hide"  the code under a button which
may read "Artcile" or may  be an abbreviation of a vendor's
name like  "CrossRef" or "PubMed" This  button will usually
lead the  user to the  full article which will  include the
DOI

**** ARTICLES FROM AN ONLINE PERIODICAL WITH DOI ASSIGNED
Lastname, F.M,  & Lastname,  F.M (Year), Title  of article,
Title of Periodical, Vol.(issue), page numbers. DOI

**** ARTICLE FROM AN ONLIINE PERIODICAL WITH NO DOI ASSIGNED
If an online ....

**** BLOG POST
Lastname,    F.M    (Year,    Month   Date),    Title    of
post. Publisher. URL

**** YOUTUBE OR OTHER STREAMING VIDEOS
Last Name,  F.M [USERNAME].  (YEAR, MONTH, DATE).  Title of
Video [VIDEO]. Streaming Service. URLk
