* TYPES OF SPEECH
** CONTENT
*** DIRECT SPEECH
When  you   directly  present  a  quotation,   observe  the
following points on style:

1. Contain the  person's words  inside the  quotation marks
   ("").

2. If  you wish  to  cut the  quotation  and add  narration
   immediately  afterwards, place  a comma  (,) before  the
   second quotation marks (").

3. If  you wish  to  end the  quotation  (and no  narration
   follows  the  immediately  afterwards), place  a  period
   before the second quotation mark (").

   Ex. "Success is never a destination," the athlete
   said.

*** INDIRECT SPEECH
If you are only reporting a speech, as opposed to directly
giving the quotation, there are two common ways for you to
do so

1. Use the  "that" cluase,  The relative pronoun  "that" is
   useful  in presenting  subordinate ideas,  A subordinate
   clause that begins with "that"  maybe attached to a main
   idea like "he said" or "she claimed"

2. Use the phrase "according to". This phrase allows you to
   name the source of your quotation

*** REMEMBER:
Your use of  direct and indirect speech depend  on the text
you're writing, If you are  writing a short story or novel,
you   are   expected   to    include   plenty   of   direct
speech. However if you are writing a news report

*** REFERENCE:

         Redoblado, S. & Costuna, A. (2015)
             Exploring Grammar and Literature 7: Direct and
             Reported   Speech,   pp.  219-220.   Brilliant
             Creations Inc.
